# Autogenerated by nbdev

d = { 'settings': { 'branch': '{branch}',
                'doc_baseurl': '/neo4jtools/',
                'doc_host': 'https://me.github.io',
                'git_url': 'https://github.com/me/neo4jtools/tree/{branch}/',
                'lib_path': 'neo4jtools'},
  'syms': {'neo4jtools.core': {}, 'neo4jtools.dwpc': {}, 'neo4jtools.graph': {}, 'neo4jtools.utils': {}}}
