# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SimpleNeo4jHTTPAPIClient": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://me.github.io/neo4jtools/"

git_url = "https://github.com/me/neo4jtools/tree/{branch}/"

def custom_doc_links(name): return None
