# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SimpleNeo4jHTTPAPIClient": "00_core.ipynb",
         "make_dwpc_query": "01_dwpc.ipynb",
         "patterns_to_query": "01_dwpc.ipynb",
         "parse_result_row_graph": "02_utils.ipynb",
         "drop_duplicates": "02_utils.ipynb",
         "parse_result_graph": "02_utils.ipynb",
         "graph_renderer": "02_utils.ipynb",
         "row_renderer": "02_utils.ipynb",
         "get_graph_for_ipycytoscape": "03_graph.ipynb",
         "draw": "03_graph.ipynb"}

modules = ["core.py",
           "dwpc.py",
           "utils.py",
           "graph.py"]

doc_url = "https://me.github.io/neo4jtools/"

git_url = "https://github.com/me/neo4jtools/tree/{branch}/"

def custom_doc_links(name): return None
