# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['SimpleNeo4jHTTPAPIClient']

# Cell
import os,json,base64
import requests
class SimpleNeo4jHTTPAPIClient:
    @staticmethod
    def get_authtoken(userid, passwd):
        authstr='{}:{}'.format(userid, passwd)
        b64token=base64.b64encode(authstr.encode())
        strtoken=b64token.decode()
        return strtoken

    def __init__(self, url, db='neo4j', userid=None, passwd=None):
        self.url=url
        self.set_serverinfo(url)
        self.setdb(db)
        self.authtoken=None
        if userid is not None:
            self.authtoken=self.get_authtoken(userid, passwd)

    def set_serverinfo(self,url):
        resp=requests.get(url)
        obj=resp.json()
        self.bolt_routing=obj['bolt_routing']
        self.transaction=obj['transaction']
        self.bolt_direct=obj['bolt_direct']
        self.neo4j_version=obj['neo4j_version']
        self.neo4j_edition=obj['neo4j_edition']

    def setdb(self, db):
        self.db=db

    def execute_read_query(self, query):

        url=self.transaction.format(databaseName=self.db) + '/commit'

        headers={
            "content-type": "application/json"
        }

        if self.authtoken is not None:
            headers['authorization']="Basic {}".format(self.authtoken)

        statement={
          "statements": [
            {
              "statement": query,
              "resultDataContents": ["row", "graph"]
            }
          ]
        }
        resp=requests.post(url,
                           data=json.dumps(statement),
                           headers=headers)

        return resp.json()

    def __repr__(self):
        return json.dumps({
            'classname':self.__class__.__name__,
            'url':self.url,
            'neo4j_version':self.neo4j_version,
            'neo4j_edition':self.neo4j_edition,
            'db':self.db,
            'auth': self.authtoken is not None
        })