# AUTOGENERATED! DO NOT EDIT! File to edit: 03_graph.ipynb (unless otherwise specified).

__all__ = ['draw_graph', 'nan']

# Cell
import json, requests
from IPython.display import IFrame
import numpy as np
nan = np.nan

def draw_graph(input_str, url='localhost:5000', width='100%', height='500'):
    resp=requests.post(
        url='http://{}/graph'.format(url),
        data={'data':input_str}
    )
    return IFrame(resp.url, width=width, height=height)