# AUTOGENERATED! DO NOT EDIT! File to edit: 03_graph.ipynb (unless otherwise specified).

__all__ = ['get_graph_for_ipycytoscape', 'draw']

# Cell
import ipycytoscape
def get_graph_for_ipycytoscape(neo4j_graph_dict):
    g={}
    g['nodes']=[{'data': {
        'id':n['identifier'],
        'name':n['name'],
        'label':n['label']
    }} for n in neo4j_graph_dict['nodes']]

    g['edges']=[{'data': {
        'source':e['start_identifier'],
        'target':e['end_identifier'],
        'type':e['type'],
        'is_directional':e['is_directional'] if 'is_directional' in e else False
    }} for e in neo4j_graph_dict['edges']]

    return g

def draw(graphs):
    style = [
        {
            'selector': 'node',
            'style': {
                'label': 'data(name)',
                'background-color': 'rgb(241, 102, 103)'
            }
        },
        {
            'selector': 'edge',
            'style': {
                'target-arrow-shape': 'triangle',
                'font-size': '8px',
                'curve-style': 'bezier',
                'label': 'data(dwpc)',
            }
        },
    ]
    widget = ipycytoscape.CytoscapeWidget()
    gs=[get_graph_for_ipycytoscape(g) for g in graphs]
    for g in gs:
        widget.graph.add_graph_from_json(g, directed=True)
    widget.set_style(style)

    return widget